# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1024, 576)
        Widget.setStyleSheet("")
        self.label_2 = QtWidgets.QLabel(Widget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1024, 576))
        self.label_2.setStyleSheet("border-image: url(img/bg_image.png) 0 0 0 0 stretch stretch;\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(Widget)
        self.groupBox.setGeometry(QtCore.QRect(750, 60, 251, 471))
        self.groupBox.setStyleSheet("background-color: rgba(255, 255, 255, 128);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(6, 51, 94)")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 61, 31))
        self.label_3.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.label_3.setObjectName("label_3")
        self.lineEdit_name = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_name.setGeometry(QtCore.QRect(70, 100, 161, 31))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.lineEdit_id = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_id.setGeometry(QtCore.QRect(70, 190, 161, 31))
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 190, 61, 31))
        self.label_4.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.label_4.setObjectName("label_4")
        self.btn_register = QtWidgets.QPushButton(self.groupBox)
        self.btn_register.setGeometry(QtCore.QRect(10, 300, 111, 41))
        self.btn_register.setObjectName("btn_register")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setGeometry(QtCore.QRect(20, 420, 211, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.btn_return = QtWidgets.QPushButton(self.groupBox)
        self.btn_return.setGeometry(QtCore.QRect(130, 300, 111, 41))
        self.btn_return.setObjectName("btn_return")
        self.video_screen = QtWidgets.QLabel(Widget)
        self.video_screen.setGeometry(QtCore.QRect(22, 130, 720, 405))
        self.video_screen.setStyleSheet("background-color: rgba(255, 255, 255, 128);")
        self.video_screen.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.video_screen.setText("")
        self.video_screen.setObjectName("video_screen")
        self.label = QtWidgets.QLabel(Widget)
        self.label.setGeometry(QtCore.QRect(20, 60, 721, 61))
        self.label.setStyleSheet("background-color: rgba(255, 255, 255, 128);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(6, 51, 94)")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_2.raise_()
        self.video_screen.raise_()
        self.groupBox.raise_()
        self.label.raise_()

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Attendance System"))
        self.groupBox.setTitle(_translate("Widget", "Add New User Data"))
        self.label_3.setText(_translate("Widget", " Name:"))
        self.label_4.setText(_translate("Widget", "     ID:"))
        self.btn_register.setText(_translate("Widget", "Regist"))
        self.btn_return.setText(_translate("Widget", "Return"))
        self.label.setText(_translate("Widget", " Stay fit your face to the screen until capturing complet!"))
