# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'attendance.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1024, 576)
        Widget.setStyleSheet("")
        self.label_background = QtWidgets.QLabel(Widget)
        self.label_background.setGeometry(QtCore.QRect(0, 0, 1024, 576))
        self.label_background.setStyleSheet("border-image: url(img/bg_image.png) 0 0 0 0 stretch stretch;\n"
"")
        self.label_background.setText("")
        self.label_background.setObjectName("label_background")
        self.btn_start = QtWidgets.QPushButton(Widget)
        self.btn_start.setGeometry(QtCore.QRect(810, 140, 161, 51))
        self.btn_start.setStyleSheet("background-color: rgba(255, 255, 255, 192);\n"
"color: rgb(2, 50, 122);\n"
"font: 75 18pt \"MS Shell Dlg 2\";")
        self.btn_start.setObjectName("btn_start")
        self.btn_end = QtWidgets.QPushButton(Widget)
        self.btn_end.setGeometry(QtCore.QRect(810, 240, 161, 51))
        self.btn_end.setStyleSheet("background-color: rgba(255, 255, 255, 192);\n"
"color: rgb(2, 50, 122);\n"
"font: 75 18pt \"MS Shell Dlg 2\";")
        self.btn_end.setObjectName("btn_end")
        self.btn_return = QtWidgets.QPushButton(Widget)
        self.btn_return.setGeometry(QtCore.QRect(810, 340, 161, 51))
        self.btn_return.setStyleSheet("background-color: rgba(255, 255, 255, 192);\n"
"color: rgb(2, 50, 122);\n"
"font: 75 18pt \"MS Shell Dlg 2\";")
        self.btn_return.setObjectName("btn_return")
        self.label_date = QtWidgets.QLabel(Widget)
        self.label_date.setGeometry(QtCore.QRect(40, 60, 201, 41))
        self.label_date.setStyleSheet("background-color: rgba(255, 255, 255, 192);\n"
"color: rgb(2, 50, 122);\n"
"font: 75 18pt \"MS Shell Dlg 2\";")
        self.label_date.setObjectName("label_date")
        self.label_end_time = QtWidgets.QLabel(Widget)
        self.label_end_time.setGeometry(QtCore.QRect(520, 60, 241, 41))
        self.label_end_time.setStyleSheet("background-color: rgba(255, 255, 255, 192);\n"
"color: rgb(2, 50, 122);\n"
"font: 75 18pt \"MS Shell Dlg 2\";")
        self.label_end_time.setObjectName("label_end_time")
        self.label_start_time = QtWidgets.QLabel(Widget)
        self.label_start_time.setGeometry(QtCore.QRect(260, 60, 241, 41))
        self.label_start_time.setStyleSheet("background-color: rgba(255, 255, 255, 192);\n"
"color: rgb(2, 50, 122);\n"
"font: 75 18pt \"MS Shell Dlg 2\";")
        self.label_start_time.setObjectName("label_start_time")
        self.video_screen = QtWidgets.QLabel(Widget)
        self.video_screen.setGeometry(QtCore.QRect(40, 130, 720, 405))
        self.video_screen.setStyleSheet("background-color: rgba(255, 255, 255, 128);")
        self.video_screen.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.video_screen.setText("")
        self.video_screen.setObjectName("video_screen")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Attendance System"))
        self.btn_start.setText(_translate("Widget", "Start"))
        self.btn_end.setText(_translate("Widget", "End"))
        self.btn_return.setText(_translate("Widget", "Return"))
        self.label_date.setText(_translate("Widget", ""))
        self.label_end_time.setText(_translate("Widget", "End Time:"))
        self.label_start_time.setText(_translate("Widget", "Start Time:"))
