# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1024, 576)
        Widget.setStyleSheet("")
        self.btn_add_new_student = QtWidgets.QPushButton(Widget)
        self.btn_add_new_student.setGeometry(QtCore.QRect(80, 180, 228, 228))
        self.btn_add_new_student.setStyleSheet("border-image: url(img/register.png) 0 0 0 0 stretch stretch;\n"
"QPushButton {\n"
"       padding: 0px;\n"
"       margin: 0px;\n"
"}\n"
"QPushButton:hover {\n"
"    border-image: url(img/register_hover.png) 0 0 0 0 stretch stretch;\n"
"}")
        self.btn_add_new_student.setText("")
        self.btn_add_new_student.setObjectName("btn_add_new_student")
        self.btn_start_attendance = QtWidgets.QPushButton(Widget)
        self.btn_start_attendance.setGeometry(QtCore.QRect(410, 180, 228, 228))
        self.btn_start_attendance.setStyleSheet("border-image: url(img/enter.png) 0 0 0 0 stretch stretch;\n"
"QPushButton {\n"
"       padding: 0px;\n"
"       margin: 0px;\n"
"}\n"
"QPushButton:hover {\n"
"    border-image: url(img/enter_hover.png) 0 0 0 0 stretch stretch;\n"
"}")
        self.btn_start_attendance.setText("")
        self.btn_start_attendance.setObjectName("btn_start_attendance")
        self.btn_exit = QtWidgets.QPushButton(Widget)
        self.btn_exit.setGeometry(QtCore.QRect(730, 180, 228, 228))
        self.btn_exit.setStyleSheet("border-image: url(img/exit.png) 0 0 0 0 stretch stretch;\n"
"QPushButton {\n"
"       padding: 0px;\n"
"       margin: 0px;\n"
"}\n"
"QPushButton:hover {\n"
"    border-image: url(img/exit_hover.png) 0 0 0 0 stretch stretch;\n"
"}")
        self.btn_exit.setText("")
        self.btn_exit.setObjectName("btn_exit")
        self.label = QtWidgets.QLabel(Widget)
        self.label.setGeometry(QtCore.QRect(80, 410, 231, 60))
        self.label.setStyleSheet("border-color: rgba(255, 255, 255, 0);\n"
"font: 75 24pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Widget)
        self.label_2.setGeometry(QtCore.QRect(420, 410, 211, 60))
        self.label_2.setStyleSheet("border-color: rgba(255, 255, 255, 0);\n"
"font: 75 24pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Widget)
        self.label_3.setGeometry(QtCore.QRect(820, 410, 61, 60))
        self.label_3.setStyleSheet("border-color: rgba(255, 255, 255, 0);\n"
"font: 75 24pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Widget)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 1024, 576))
        self.label_4.setStyleSheet("border-image: url(img/bg_image.png) 0 0 0 0 stretch stretch;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        self.btn_add_new_student.raise_()
        self.btn_start_attendance.raise_()
        self.btn_exit.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Attendance System"))
        self.label.setText(_translate("Widget", "Add New Student"))
        self.label_2.setText(_translate("Widget", "Start Attendance"))
        self.label_3.setText(_translate("Widget", "Exit"))
