# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1024, 576)
        Widget.setStyleSheet("")
        self.label_2 = QtWidgets.QLabel(Widget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1024, 576))
        self.label_2.setStyleSheet("border-image: url(img/bg_image.png) 0 0 0 0 stretch stretch;\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.table_user_list = QtWidgets.QTableWidget(Widget)
        self.table_user_list.setGeometry(QtCore.QRect(40, 40, 761, 501))
        self.table_user_list.setStyleSheet("background-color: rgba(255, 255, 255, 192);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.table_user_list.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.table_user_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_user_list.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.table_user_list.setColumnCount(4)
        self.table_user_list.setObjectName("table_user_list")
        self.table_user_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_user_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_user_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_user_list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_user_list.setHorizontalHeaderItem(3, item)
        self.table_user_list.horizontalHeader().setCascadingSectionResizes(True)
        self.table_user_list.verticalHeader().setCascadingSectionResizes(True)
        self.table_user_list.verticalHeader().setDefaultSectionSize(64)
        self.table_user_list.verticalHeader().setMinimumSectionSize(64)
        self.table_user_list.verticalHeader().setStretchLastSection(False)
        self.btn_add = QtWidgets.QPushButton(Widget)
        self.btn_add.setGeometry(QtCore.QRect(840, 140, 141, 61))
        self.btn_add.setStyleSheet("background-color: rgba(255, 255, 255, 192);\n"
"color: rgb(6, 47, 111);\n"
"font: 75 24pt \"MS Shell Dlg 2\";")
        self.btn_add.setObjectName("btn_add")
        self.btn_return = QtWidgets.QPushButton(Widget)
        self.btn_return.setGeometry(QtCore.QRect(840, 340, 141, 61))
        self.btn_return.setStyleSheet("background-color: rgba(255, 255, 255, 192);\n"
"color: rgb(6, 47, 111);\n"
"font: 75 24pt \"MS Shell Dlg 2\";")
        self.btn_return.setObjectName("btn_return")
        self.btn_train = QtWidgets.QPushButton(Widget)
        self.btn_train.setGeometry(QtCore.QRect(840, 240, 141, 61))
        self.btn_train.setStyleSheet("background-color: rgba(255, 255, 255, 192);\n"
"color: rgb(6, 47, 111);\n"
"font: 75 24pt \"MS Shell Dlg 2\";")
        self.btn_train.setObjectName("btn_train")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Attendance System"))
        self.table_user_list.setSortingEnabled(True)
        item = self.table_user_list.horizontalHeaderItem(0)
        item.setText(_translate("Widget", "Avatar"))
        item = self.table_user_list.horizontalHeaderItem(1)
        item.setText(_translate("Widget", "Full Name"))
        item = self.table_user_list.horizontalHeaderItem(2)
        item.setText(_translate("Widget", "ID"))
        item = self.table_user_list.horizontalHeaderItem(3)
        item.setText(_translate("Widget", "Action"))
        self.btn_add.setText(_translate("Widget", "Add"))
        self.btn_return.setText(_translate("Widget", "Return"))
        self.btn_train.setText(_translate("Widget", "Train"))
